### ISSUE TITLE
How to "add_event_listener" using this library?

### ISSUE THREAD

**Issue by Niedzwiedzw** [Demonthos/sledgehammer-bindgen#6]
Hello, I'd like to try swapping wasm_bindgen for this in my implementation. Is there an example of how would I go about passing a closure into `addEventListener()` parameter?

**Comment by ealmloff** [comment]
Sledgehammer bindgen doesn't handle complex objects like closures/function pointers. You can use wasm-bindgen in combination with sledgehammer-bindgen to handler events. For example, Dioxus uses sledgehammer and wasm-bindgen to set up a synthetic event system [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/interpreter/src/sledgehammer_bindings.rs#L226)
